WebApplication1/Controllers/HelloWorldController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HelloWorldController : Controller
    {
        static List<Student> stuList=new List<Student> ();

        // GET: HelloWorld
        public ActionResult Index()
        {
            return View();
        }

    
        public ActionResult Welcome(String username, String sex, int n)
        {
            if (sex.Equals( "男"))
            {
                ViewBag.Message = "欢迎" + username + "先生";
            }
            else if (sex.Equals("女"))
            {
                ViewBag.Message = "欢迎" + username + "女士";
            }

            ViewBag.Count = n;

            return View();
        }


        public void Add(Student stu)
        {
            var result = from s in stuList
                         where s.id == stu.id
                         select s;

            if (result.Count< Student >() > 0)
            {
                Response.Write("<script>alert('该记录已存在')</script>");
            }
            else
            {
                stuList.Add(stu);

                ViewBag.Count = stuList.Count;
                Response.Write("<script>alert('学生信息添加成功')</script>");
            }
        }

        public ActionResult Details(int id)
        {
            var result = from s in stuList
                         where s.id == id
                         select s;
            Student stu = result.FirstOrDefault<Student>();


            if (stu == null)
            {
                return View("None");
            }
            else
            {
                return View(stu);
            }
        }


        public ActionResult List()
        {
            //ViewBag.List = stuList;
            return View(stuList);
        }

    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                    <li>@Html.ActionLink("你好世界", "Index", "HelloWorld")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site2.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <ul id="menu">
        <li>@Html.ActionLink("首页", "Index", "Home")</li>
        <li>@Html.ActionLink("关于", "About", "Home")</li>
        <li>@Html.ActionLink("联系", "Contact", "Home")</li>
    </ul>
    <section id="main">
        @RenderBody()
        <p>Copyright WUST 2017. All Rights Reserved.</p>
    </section>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>